name: Pre-commit
on:
  push:
    branches:
      - main

jobs:
  pre-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Build and test
        run: |
          dotnet format
          dotnet build --configuration Release
          dotnet test --no-restore --verbosity normal
