name: Documentacion
on:
  push:
    branches:
    - main
jobs:
  build:
    name: Crear Documentacion
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Configurar entorno de .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Restaurar paquetes, compilar y ejecutar proyecto 
      run: |
          dotnet restore
          dotnet build --configuration Debug
          timeout -k 5s 6s dotnet run --project ./RedocPro/RedocPro.csproj  --configuration Debug || true   
          
    - name: Configuracion Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Generate Changelog
      run: git log --pretty=format:"- %s" > CHANGELOG.md
      
    - name: Generacion de Postman
      run: |
         npm i -g openapi-to-postmanv2
         openapi2postmanv2 -s ./swagger.json -o ./postman_collection.json
         sed -i '1s/^/{"collection":/' postman_collection.json
         echo '}' >> postman_collection.json
        
    - name: Update Postman Collection
      run: |
          sudo apt-get install curl
          npm install -g newman
          curl -X PUT -H "Content-Type: application/json" -H "X-Api-Key: ${{ secrets.POSTMAN_API_KEY }}" -d @postman_collection.json "https://api.postman.com/collections/27712020-db7469c0-0df4-4bb8-bf0f-c04c59dde495"
    
    - name: Actualizar rama main
      run: |
          git checkout main
           git checkout main
          if [[ -n $(git status -s) ]]; then
            git stash
            git pull origin main
            git stash apply
            git add .
            git -c user.name="Guillermo Coba Montoya" -c user.email="guillermo.coba@digitalfemsa.com" commit -m "[SPPP-000]: Actualización de recursos"
            git push origin main
          else
            echo "No hay cambios para actualizar en la rama main"
          fi
    
    - name: Instalacion de Redoc CLI y Deploy
      run: |
        npm install -g redoc-cli@latest
        redoc-cli bundle ./swagger.json --output ./index.html

    - name: Deploy en GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        exclude_assets: '.github,.vs,RedocPro,RedocPro.sln,.gitignore'
        force_orphan: true
