name: Documentacion
on:
  push:
    branches:
    - main
jobs:
  build:
    name: Crear Documentacion
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configurar entorno de .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'
    - name: Restaurar paquetes, compilar y ejecutar proyecto 
      run: |
          dotnet restore
          dotnet build --configuration Debug
          timeout -k 5s 6s dotnet run --project ./RedocPro/RedocPro.csproj  -- output ./openapi-snippet || true          
    - name: Actualizar rama main
      run: |
            git checkout main
            git config user.name "user"
            git config user.email "email"
            if [[ -n $(git status -s) ]]; then
                git add .
                git commit -m "Actualizar archivo JSON"
               git push origin main
            else
               echo "No hay cambios para actualizar en la rama main"
            fi
    - name: Instalacion de Redoc CLI y Deploy
      run: |
        npm install -g redoc-cli@latest
        redoc-cli bundle ./openapi-snippet -o ./index.html
    - name: Desplegar documentación en Redoc
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./redoc-static
        exclude_assets: '.github,.vs,RedocPro,RedocPro.sln,.gitignore'
