name: Documentacion
on:
  push:
    branches:
    - main
jobs:
  build:
    name: Crear Documentacion
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Configurar entorno de .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Restaurar paquetes, compilar y ejecutar proyecto 
      run: |
          dotnet restore
          dotnet build --configuration Debug
          timeout -k 5s 6s dotnet run --project ./RedocPro/RedocPro.csproj  --configuration Debug || true   
          
    - name: Configuracion Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Resources in Powershell and commit to Main
      run: pwsh -File ./tools/resources.ps1
  
    - name: Instalacion de Redoc CLI y Deploy
      run: npm install -g redoc-cli@latest
    - name: Build and Deploy Versions
      run: |
        files=$(find ./swagger_files -name "swaggerv*.json")
          for file in $files; do
          version=$(basename "$file" .json | sed 's/swagger_//')
          echo "Building and deploying Version $version"
          redoc-cli bundle "$file" --output "./docs/$version/index.html"
        done

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: ./docs
        clean: true
